[server]
host: 0.0.0.0
port: 7125
max_upload_size: 1024
klippy_uds_address: /run/klippy.sock

[file_manager]
enable_object_processing: False

[authorization]
cors_domains:
    *://*.local
    *://*.lan
trusted_clients:
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    FE80::/10
    ::1/128

[octoprint_compat]

[history]

[announcements]
subscriptions:
    mainsail

[webcam webcam]
stream_url: /webcam/?action=stream
snapshot_url: /webcam/?action=snapshot
